import { IoTBoardDefinition } from '@aether/shared';

export const PREDEFINED_BOARDS: IoTBoardDefinition[] = [
  // ─── ESP32 FAMILY ───
  {
    boardId: 'esp32-dev-module',
    name: 'ESP32 Dev Module',
    family: 'ESP32',
    chip: 'ESP32-D0WDQ6 (Xtensa Dual-Core 240MHz)',
    architecture: 'Xtensa LX6',
    flashSizeMb: 4,
    ramSizeKb: 520,
    gpioCount: 34,
    adcChannels: 18,
    wifiSupport: true,
    bluetoothSupport: true,
    mqttSupport: true,
    tlsSupport: true,
    arduinoCore: 'esp32 by Espressif Systems',
    boardManagerUrl: 'https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json',
    wifiHeader: '<WiFi.h>',
    requiredLibraries: ['WiFi.h', 'WiFiClientSecure.h', 'PubSubClient.h', 'ArduinoJson.h', 'DHT.h'],
    recommendedPins: {
      soilMoisturePin: 'GPIO 34 (ADC1_CH6)',
      dhtPin: 'GPIO 4',
      relayPumpPin: 'GPIO 26',
      flowRatePin: 'GPIO 27',
      pirMotionPin: 'GPIO 14',
    },
    validPins: [
      { pinName: 'GPIO 34', gpioNumber: '34', supportedModes: ['ANALOG_IN'], recommendedFor: 'SOIL_MOISTURE' },
      { pinName: 'GPIO 35', gpioNumber: '35', supportedModes: ['ANALOG_IN'], recommendedFor: 'ANALOG_SENSOR' },
      { pinName: 'GPIO 4', gpioNumber: '4', supportedModes: ['DIGITAL_IO', 'PWM'], recommendedFor: 'DHT_SENSOR' },
      { pinName: 'GPIO 26', gpioNumber: '26', supportedModes: ['DIGITAL_IO', 'PWM'], recommendedFor: 'RELAY_PUMP' },
      { pinName: 'GPIO 27', gpioNumber: '27', supportedModes: ['DIGITAL_IO', 'PWM'], recommendedFor: 'FLOW_RATE' },
      { pinName: 'GPIO 14', gpioNumber: '14', supportedModes: ['DIGITAL_IO'], recommendedFor: 'PIR_MOTION' },
      { pinName: 'GPIO 18', gpioNumber: '18', supportedModes: ['DIGITAL_IO', 'SPI'] },
      { pinName: 'GPIO 19', gpioNumber: '19', supportedModes: ['DIGITAL_IO', 'SPI'] },
      { pinName: 'GPIO 21', gpioNumber: '21', supportedModes: ['DIGITAL_IO', 'I2C'] },
      { pinName: 'GPIO 22', gpioNumber: '22', supportedModes: ['DIGITAL_IO', 'I2C'] },
    ],
  },
  {
    boardId: 'esp32-wroom-32',
    name: 'ESP32-WROOM-32',
    family: 'ESP32',
    chip: 'ESP32-WROOM-32D',
    architecture: 'Xtensa LX6',
    flashSizeMb: 4,
    ramSizeKb: 520,
    gpioCount: 32,
    adcChannels: 18,
    wifiSupport: true,
    bluetoothSupport: true,
    mqttSupport: true,
    tlsSupport: true,
    arduinoCore: 'esp32 by Espressif Systems',
    boardManagerUrl: 'https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json',
    wifiHeader: '<WiFi.h>',
    requiredLibraries: ['WiFi.h', 'WiFiClientSecure.h', 'PubSubClient.h', 'ArduinoJson.h', 'DHT.h'],
    recommendedPins: {
      soilMoisturePin: 'GPIO 34',
      dhtPin: 'GPIO 4',
      relayPumpPin: 'GPIO 26',
      flowRatePin: 'GPIO 27',
      pirMotionPin: 'GPIO 14',
    },
    validPins: [
      { pinName: 'GPIO 34', gpioNumber: '34', supportedModes: ['ANALOG_IN'] },
      { pinName: 'GPIO 4', gpioNumber: '4', supportedModes: ['DIGITAL_IO'] },
      { pinName: 'GPIO 26', gpioNumber: '26', supportedModes: ['DIGITAL_IO'] },
      { pinName: 'GPIO 27', gpioNumber: '27', supportedModes: ['DIGITAL_IO'] },
    ],
  },
  {
    boardId: 'esp32-s3-dev',
    name: 'ESP32-S3 Dev Module',
    family: 'ESP32',
    chip: 'ESP32-S3 (Xtensa Dual-Core 240MHz + Vector)',
    architecture: 'Xtensa LX7',
    flashSizeMb: 8,
    ramSizeKb: 512,
    gpioCount: 45,
    adcChannels: 20,
    wifiSupport: true,
    bluetoothSupport: true,
    mqttSupport: true,
    tlsSupport: true,
    arduinoCore: 'esp32 by Espressif Systems',
    boardManagerUrl: 'https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json',
    wifiHeader: '<WiFi.h>',
    requiredLibraries: ['WiFi.h', 'WiFiClientSecure.h', 'PubSubClient.h', 'ArduinoJson.h', 'DHT.h'],
    recommendedPins: {
      soilMoisturePin: 'GPIO 1',
      dhtPin: 'GPIO 4',
      relayPumpPin: 'GPIO 10',
      flowRatePin: 'GPIO 11',
      pirMotionPin: 'GPIO 12',
    },
    validPins: [
      { pinName: 'GPIO 1', gpioNumber: '1', supportedModes: ['ANALOG_IN'] },
      { pinName: 'GPIO 4', gpioNumber: '4', supportedModes: ['DIGITAL_IO'] },
      { pinName: 'GPIO 10', gpioNumber: '10', supportedModes: ['DIGITAL_IO'] },
    ],
  },
  {
    boardId: 'esp32-c3-dev',
    name: 'ESP32-C3 RISC-V Dev',
    family: 'ESP32',
    chip: 'ESP32-C3 Single-Core 160MHz RISC-V',
    architecture: 'RISC-V 32-bit',
    flashSizeMb: 4,
    ramSizeKb: 400,
    gpioCount: 22,
    adcChannels: 6,
    wifiSupport: true,
    bluetoothSupport: true,
    mqttSupport: true,
    tlsSupport: true,
    arduinoCore: 'esp32 by Espressif Systems',
    boardManagerUrl: 'https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json',
    wifiHeader: '<WiFi.h>',
    requiredLibraries: ['WiFi.h', 'WiFiClientSecure.h', 'PubSubClient.h', 'ArduinoJson.h', 'DHT.h'],
    recommendedPins: {
      soilMoisturePin: 'GPIO 0',
      dhtPin: 'GPIO 1',
      relayPumpPin: 'GPIO 4',
      flowRatePin: 'GPIO 5',
      pirMotionPin: 'GPIO 6',
    },
    validPins: [
      { pinName: 'GPIO 0', gpioNumber: '0', supportedModes: ['ANALOG_IN'] },
      { pinName: 'GPIO 1', gpioNumber: '1', supportedModes: ['DIGITAL_IO'] },
      { pinName: 'GPIO 4', gpioNumber: '4', supportedModes: ['DIGITAL_IO'] },
    ],
  },

  // ─── ESP8266 FAMILY ───
  {
    boardId: 'nodemcu-1.0-esp12e',
    name: 'NodeMCU 1.0 (ESP-12E Module)',
    family: 'ESP8266',
    chip: 'ESP8266EX (Tensilica 80MHz)',
    architecture: 'Tensilica L106',
    flashSizeMb: 4,
    ramSizeKb: 80,
    gpioCount: 11,
    adcChannels: 1,
    wifiSupport: true,
    bluetoothSupport: false,
    mqttSupport: true,
    tlsSupport: true,
    arduinoCore: 'esp8266 by ESP8266 Community',
    boardManagerUrl: 'https://arduino.esp8266.com/stable/package_esp8266com_index.json',
    wifiHeader: '<ESP8266WiFi.h>',
    requiredLibraries: ['ESP8266WiFi.h', 'WiFiClientSecure.h', 'PubSubClient.h', 'ArduinoJson.h', 'DHT.h'],
    recommendedPins: {
      soilMoisturePin: 'A0 (ADC0)',
      dhtPin: 'D2 (GPIO 4)',
      relayPumpPin: 'D1 (GPIO 5)',
      flowRatePin: 'D5 (GPIO 14)',
      pirMotionPin: 'D6 (GPIO 12)',
    },
    validPins: [
      { pinName: 'A0 (ADC0)', gpioNumber: 'A0', supportedModes: ['ANALOG_IN'], recommendedFor: 'SOIL_MOISTURE' },
      { pinName: 'D1 (GPIO 5)', gpioNumber: '5', supportedModes: ['DIGITAL_IO', 'PWM', 'I2C'], recommendedFor: 'RELAY_PUMP' },
      { pinName: 'D2 (GPIO 4)', gpioNumber: '4', supportedModes: ['DIGITAL_IO', 'PWM', 'I2C'], recommendedFor: 'DHT_SENSOR' },
      { pinName: 'D5 (GPIO 14)', gpioNumber: '14', supportedModes: ['DIGITAL_IO', 'SPI'], recommendedFor: 'FLOW_RATE' },
      { pinName: 'D6 (GPIO 12)', gpioNumber: '12', supportedModes: ['DIGITAL_IO', 'SPI'], recommendedFor: 'PIR_MOTION' },
      { pinName: 'D7 (GPIO 13)', gpioNumber: '13', supportedModes: ['DIGITAL_IO', 'SPI'] },
    ],
  },
  {
    boardId: 'wemos-d1-mini',
    name: 'Wemos D1 Mini (ESP8266)',
    family: 'ESP8266',
    chip: 'ESP8266EX Compact',
    architecture: 'Tensilica L106',
    flashSizeMb: 4,
    ramSizeKb: 80,
    gpioCount: 11,
    adcChannels: 1,
    wifiSupport: true,
    bluetoothSupport: false,
    mqttSupport: true,
    tlsSupport: true,
    arduinoCore: 'esp8266 by ESP8266 Community',
    boardManagerUrl: 'https://arduino.esp8266.com/stable/package_esp8266com_index.json',
    wifiHeader: '<ESP8266WiFi.h>',
    requiredLibraries: ['ESP8266WiFi.h', 'WiFiClientSecure.h', 'PubSubClient.h', 'ArduinoJson.h', 'DHT.h'],
    recommendedPins: {
      soilMoisturePin: 'A0',
      dhtPin: 'D2 (GPIO 4)',
      relayPumpPin: 'D1 (GPIO 5)',
      flowRatePin: 'D5 (GPIO 14)',
      pirMotionPin: 'D6 (GPIO 12)',
    },
    validPins: [
      { pinName: 'A0', gpioNumber: 'A0', supportedModes: ['ANALOG_IN'] },
      { pinName: 'D1 (GPIO 5)', gpioNumber: '5', supportedModes: ['DIGITAL_IO'] },
      { pinName: 'D2 (GPIO 4)', gpioNumber: '4', supportedModes: ['DIGITAL_IO'] },
    ],
  },
  {
    boardId: 'esp-01s',
    name: 'ESP-01S Ultra-Compact Module',
    family: 'ESP8266',
    chip: 'ESP8266EX',
    architecture: 'Tensilica L106',
    flashSizeMb: 1,
    ramSizeKb: 80,
    gpioCount: 4,
    adcChannels: 0,
    wifiSupport: true,
    bluetoothSupport: false,
    mqttSupport: true,
    tlsSupport: false,
    arduinoCore: 'esp8266 by ESP8266 Community',
    boardManagerUrl: 'https://arduino.esp8266.com/stable/package_esp8266com_index.json',
    wifiHeader: '<ESP8266WiFi.h>',
    requiredLibraries: ['ESP8266WiFi.h', 'PubSubClient.h', 'ArduinoJson.h', 'DHT.h'],
    recommendedPins: {
      soilMoisturePin: 'None (No ADC)',
      dhtPin: 'GPIO 2',
      relayPumpPin: 'GPIO 0',
      flowRatePin: 'GPIO 3 (RX)',
      pirMotionPin: 'GPIO 1 (TX)',
    },
    validPins: [
      { pinName: 'GPIO 0', gpioNumber: '0', supportedModes: ['DIGITAL_IO'] },
      { pinName: 'GPIO 2', gpioNumber: '2', supportedModes: ['DIGITAL_IO'] },
    ],
  },
];
